#!/usr/bin/env python3
"""Export documentation artwork from the packaged native icon, without redrawing it.

Usage: python3 Scripts/export-brand-assets.py --app dist/0.1.3/Tapas.app
The app's ICNS is generated by DesignRendering.exportIcon using PintxoMark.
"""
import argparse
import base64
from pathlib import Path
import shutil
import subprocess
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--app', required=True, type=Path, help='Packaged Tapas.app whose icon is the approved artwork')
    args = parser.parse_args()
    source = args.app.resolve() / 'Contents/Resources/Tapas.icns'
    if not source.is_file():
        parser.error(f'No native icon at {source}')
    destination = Path(__file__).resolve().parents[1] / 'assets/tapas'
    destination.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='tapas-brand-') as temporary:
        iconset = Path(temporary) / 'Tapas.iconset'
        subprocess.run(['iconutil', '-c', 'iconset', str(source), '-o', str(iconset)], check=True)
        # Preserve the exact native pixels, including alpha, ink shadows and shape details.
        png = iconset / 'icon_512x512@2x.png'
        if not png.is_file():
            png = iconset / 'icon_512x512.png'
        if not png.is_file():
            raise SystemExit('The packaged icon has no 512px or 1024px representation.')
        shutil.copyfile(png, destination / 'icon.png')
        # Keep old SVG links working with identical artwork, not a second hand-drawn logo.
        payload = base64.b64encode(png.read_bytes()).decode('ascii')
        (destination / 'icon.svg').write_text(
            '<!-- Generated by Scripts/export-brand-assets.py from the packaged native icon. Do not redraw. -->\n'
            '<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">'
            '<title>Tapas</title><image width="1024" height="1024" href="data:image/png;base64,'
            + payload + '"/></svg>\n'
        )
    print('Exported assets/tapas/icon.png and the matching icon.svg compatibility wrapper.')


if __name__ == '__main__':
    main()
